//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiPlex.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\pierr_000\\Videos\\Movies")]
        public string PlexMovieFolderPath {
            get {
                return ((string)(this["PlexMovieFolderPath"]));
            }
            set {
                this["PlexMovieFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\pierr_000\\Videos\\TV Shows")]
        public string PlexTvShowFolderPath {
            get {
                return ((string)(this["PlexTvShowFolderPath"]));
            }
            set {
                this["PlexTvShowFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Plex\\Plex Media Server\\Plex Media Scanner.exe")]
        public string PlexMediaScannerPath {
            get {
                return ((string)(this["PlexMediaScannerPath"]));
            }
            set {
                this["PlexMediaScannerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\pierr_000\\Downloads")]
        public string DonwloadFolderPath {
            get {
                return ((string)(this["DonwloadFolderPath"]));
            }
            set {
                this["DonwloadFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:32400/web/")]
        public string PlexMediaManagerUrl {
            get {
                return ((string)(this["PlexMediaManagerUrl"]));
            }
            set {
                this["PlexMediaManagerUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Plex\\Plex Media Server\\Plex Media Server.exe")]
        public string PlexMediaServerPath {
            get {
                return ((string)(this["PlexMediaServerPath"]));
            }
            set {
                this["PlexMediaServerPath"] = value;
            }
        }
    }
}
